# Production overrides
version: '3.8'
services:
  flask_app:
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  fastapi_app:
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 2G
          cpus: '1.0'