version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:kushal07@db:5432/aivivid
    depends_on:
      - db
      - redis

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://postgres:kushal07@db:5432/aivivid
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kushal07
      - POSTGRES_DB=aivivid
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  ml_models:

networks:
  aivivid_network:
    driver: bridge