global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['flask_app:5000']
    metrics_path: '/metrics'

  - job_name: 'fastapi_app'
    static_configs:
      - targets: ['fastapi_app:8000']
    metrics_path: '/metrics'

  - job_name: 'tensorflow_serving'
    static_configs:
      - targets: ['tensorflow_serving:8501']
    metrics_path: '/monitoring/prometheus/metrics'

  - job_name: 'node_auth'
    static_configs:
      - targets: ['node_auth:3000']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'container_metrics'
    static_configs:
      - targets: ['flask_app:5000']
    metrics_path: '/container-metrics'
    scrape_interval: 5s